# Generated by Django 5.0.4 on 2024-04-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reason',
            field=models.TextField(default='Kiritilmagan'),
        ),
    ]
