# Generated by Django 5.1.5 on 2025-01-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
