# Generated by Django 5.1.5 on 2025-02-04 12:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
