# Generated by Django 5.0.4 on 2024-04-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_article_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
